### PR TITLE
Added t5xxl clip support

### PR DESCRIPTION
**Pull request by hronoas**
t5xxl clip support + flux example

### CODE REVIEW

**Review by huchenlei — CHANGES_REQUESTED** [review]
image
[flux_omost_min_repro.json](https://github.com/user-attachments/files/16488712/flux_omost_min_repro.json)

Produces pure black output according to minimal workflow testintg.

**Comment by hronoas** [comment]
> Produces pure black output according to minimal workflow testintg.

The same situation after drag and drop json, but it starts working after reloading the page or change noise_seed

**Comment by huchenlei** [comment]
> > Produces pure black output according to minimal workflow testintg.
> 
> The same situation after drag and drop json, but it starts working after reloading the page or change noise_seed

Tested. Not working. BTW, the comparison workflow is using original prompt (LLM input) as prompt input for text encoder. So the flux part essentially bypass all omost logic.

image

**Review by huchenlei — CHANGES_REQUESTED** [review]
Need to update workflow to properly reflect code change.

**Pull request closed without merging**
